# Generated by Django 5.2.15 on 2026-06-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=500)),
                ('pickup_location', models.CharField(max_length=500)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('current_cycle_used', models.FloatField(default=0)),
                ('distance_miles', models.FloatField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('eta_hours', models.FloatField(blank=True, null=True)),
                ('days_required', models.IntegerField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('current_coords', models.JSONField(blank=True, null=True)),
                ('pickup_coords', models.JSONField(blank=True, null=True)),
                ('dropoff_coords', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('fuel', 'Fuel Stop'), ('break', 'Break'), ('rest', 'Overnight Rest'), ('restart', '34-Hour Restart'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('coords', models.JSONField(blank=True, null=True)),
                ('duration_hours', models.FloatField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('day_number', models.IntegerField(default=1)),
                ('elapsed_hours', models.FloatField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date_label', models.CharField(blank=True, max_length=50)),
                ('log_data', models.JSONField(blank=True, null=True)),
                ('totals', models.JSONField(blank=True, null=True)),
                ('remarks', models.JSONField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='api.trip')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
